name: Read JSON Practice

on:
  push:
  workflow_dispatch:

jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Download repo onto runner
        uses: actions/checkout@v6

      - name: Show files
        run: ls

      - name: Print raw JSON
        run: cat data.json

      - name: Run Python script
        run: python read_json.py
