name: Read repo data

on:
  workflow_dispatch: {}

jobs:
  build-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Python script
        run: python scripts/build_payload.py
